### ISSUE TITLE
API Por do sol error

### ISSUE THREAD

**Issue by AlexandreXYZ** [AlexandreXYZ/CGE-Calibrador-de-Gnomon-Eletronico#22]
Ontem e hoje depois de um tempo os graficos param de funcionar e aparece o seguinte erro:

![image](https://user-images.githubusercontent.com/61050276/143724053-76ddf0f6-c56a-4cbb-84b4-64e96b6259c7.png)

A parte front-end não foi modificada e estava funcionando durante a tarde, mas durante a noite ele retorna esse erro.

@k1vz

**Comment by k1vz** [comment]
po bixo, mostra oq ela ta retornando ne

**Comment by k1vz** [comment]
temos q dar um merge nas branchs ..

**Comment by AlexandreXYZ** [comment]
> po bixo, mostra oq ela ta retornando ne

Só isso, no server ele não retorna nada, testa ai cara

**Comment by AlexandreXYZ** [comment]
O erro estava sendo causado pela API da branch estar desatualizada.
Erro resolvido.
